distros/dashing/osrf-testing-tools-cpp/default.nix
distros/dashing/test-osrf-testing-tools-cpp/default.nix
distros/dashing/tracetools-launch/default.nix
distros/dashing/tracetools-test/default.nix
distros/eloquent/osrf-testing-tools-cpp/default.nix
distros/eloquent/test-osrf-testing-tools-cpp/default.nix
distros/foxy/gazebo-msgs/default.nix
distros/foxy/gazebo-plugins/default.nix
distros/foxy/gazebo-ros-pkgs/default.nix
distros/foxy/gazebo-ros/default.nix
distros/foxy/osrf-testing-tools-cpp/default.nix
distros/foxy/rviz-assimp-vendor/default.nix
distros/foxy/rviz-common/default.nix
distros/foxy/rviz-default-plugins/default.nix
distros/foxy/rviz-ogre-vendor/default.nix
distros/foxy/rviz-rendering-tests/default.nix
distros/foxy/rviz-rendering/default.nix
distros/foxy/rviz-visual-testing-framework/default.nix
distros/foxy/rviz2/default.nix
distros/foxy/test-osrf-testing-tools-cpp/default.nix
distros/kinetic/librealsense2/default.nix
distros/kinetic/soem/default.nix
distros/kinetic/urg-stamped/default.nix
distros/melodic/rviz/default.nix
distros/melodic/soem/default.nix
distros/melodic/ur-msgs/default.nix
distros/melodic/urg-stamped/default.nix
distros/noetic/rviz/default.nix
distros/noetic/soem/default.nix
distros/noetic/urg-stamped/default.nix

Superflore Nix generator began regeneration of all packages  from ROS distro ['dashing', 'eloquent', 'foxy', 'kinetic', 'melodic', 'noetic'] from nix-ros-overlay commit 9d7a6c25ba4f06a07d18cb2964a117131abf358a.
```
superflore-gen-nix --tar-archive-dir /home/runner/work/_temp/tar --output-repository-path . --all
```
Changes:
========
Foxy Changes:
-------------
* *gazebo-msgs 3.5.0-r1 --> 3.5.0-r2*
* *gazebo-plugins 3.5.0-r1 --> 3.5.0-r2*
* *gazebo-ros 3.5.0-r1 --> 3.5.0-r2*
* *gazebo-ros-pkgs 3.5.0-r1 --> 3.5.0-r2*
* *rviz-assimp-vendor 8.1.1-r1 --> 8.2.0-r1*
* *rviz-common 8.1.1-r1 --> 8.2.0-r1*
* *rviz-default-plugins 8.1.1-r1 --> 8.2.0-r1*
* *rviz-ogre-vendor 8.1.1-r1 --> 8.2.0-r1*
* *rviz-rendering 8.1.1-r1 --> …

rosdistro sync, Fri Jun 26 12:52:25 2020

---

distros/distro-overlay.nix

Hi @lopsided98 
Thanks for the great work on this overlay!
This fix is similar to the one introduced in https://github.com/lopsided98/nix-ros-overlay/commit/c0ebfc2faa28d8b80e8617dddc41c2a41db9ab16 but for RViZ

Call wrapQtApp on rviz executable

---

distros/foxy/generated.nix
distros/foxy/moveit-core/default.nix
distros/melodic/cob-obstacle-distance-moveit/default.nix
distros/melodic/cob-obstacle-distance/default.nix
distros/melodic/fcl-catkin/default.nix
distros/melodic/generated.nix
distros/melodic/moveit-core/default.nix
distros/melodic/robot-body-filter/default.nix
distros/noetic/cob-obstacle-distance/default.nix
distros/noetic/fcl-catkin/default.nix
distros/noetic/fcl/default.nix
distros/noetic/generated.nix

Superflore Nix generator began regeneration of all packages  from ROS distro ['dashing', 'foxy', 'galactic', 'melodic', 'noetic'] from nix-ros-overlay commit f91e6e19b58807f5af7e87a6b7bd253df843a329.
```
superflore-gen-nix --tar-archive-dir /home/runner/work/_temp/tar --output-repository-path . --upstream-branch staging --all
```
Changes:
========
Foxy Changes:
-------------
* *moveit-core 2.1.3-r1*
Melodic Changes:
----------------
* *cob-obstacle-distance 0.8.12-r1*
* *cob-obstacle-distance-moveit 0.7.5-r1*
* *fcl-catkin 0.6.1-r2*
* *moveit-core 1.0.8-r1*
* *robot-body-filter 1.1.9-r1*
Noetic Changes:
---------------
* *cob-obstacle-distance 0.8.13-r1*
* *fcl 0.6.1-r3*
* *fcl-catkin 0.6.1-r1*
Missing Dependencies: …

rosdistro sync, Sat May 29 02:26:02 2021

---

pkgs/colcon/notification.nix
pkgs/colcon/output.nix
pkgs/colcon/parallel-executor.nix
pkgs/default.nix

These are needed for QoL when building multi-package workspaces with colcon in a developer context. I've handled the two use-cases separately— defining `colcon` for interactive use, with these plugins included, and then a separate, much more stripped down `colconMinimal` to be used with derivations.
Not sure if you have much in the way of tooling to monitor these kinds of packages for new versions or whatever else, but I've been pleased with what https://github.com/nix-community/pip2nix has been able to generate based just on `requirements.txt` files. The resulting derivations are not publication-quality (missing all metadata, for example), but possibly that's worth it in some of these cases.

Add output, notification, parallel plugins for colcon.

---

distros/distro-overlay.nix

Fixes error:
> This application failed to start because no Qt platform plugin could be initialized.

rqt-console: wrap Qt

---

distros/distro-overlay.nix
distros/ros1-overlay.nix
flake.lock

By making sip-4 compatible with pyqt5 which is required by python-qt-binding, a dependency of rviz, using this patch:
https://aur.archlinux.org/cgit/aur.git/plain/restore-sip4-support.patch?h=python-pyqt5-sip4&id=6e712e6c588d550a1a6f83c1b37c2c9135aae6ba
Should fix https://github.com/lopsided98/nix-ros-overlay/issues/227
Signed-off-by: Amneesh Singh <natto@weirdnatto.in>

distros/ros1-overlay: fix rviz build

---

pkgs/colcon/core.nix
pkgs/colcon/defaults.nix
pkgs/default.nix

This extension allows one to configure colcon defaults in `~/.colcon/default.yaml`. It requires colcon-core ≥ 0.12 so I updated it as well. I tested the result by building my project and found no problems.
I left the maintainer field of the colcon-defaults expression set to @lopsided98 (the same as in other extensions). Let me know if you prefer having me there instead.

Add colcon-defaults extension

---

README.md
examples/ros2-basic.nix
examples/turtlebot3-gazebo.nix
flake.nix

This add the examples to the flake and automatically enable the binary cache. With this, one can simply run the example as:
```sh
nix develop github:wentasah/nix-ros-overlay/configure-cache-in-flake#example-turtlebot3-gazebo
```

flake: Configure the binary cache and add examples

---

pkgs/ignition/transport/default.nix

Building a program depending on ignition-transport would fail with underlinking:
/nix/store/039g378vc3pc3dvi9dzdlrd0i4q93qwf-binutils-2.39/bin/ld: warning: libsodium.so.23, needed by /nix/store/nfv1rmk3ah4dy81qnshylwibbn7dpxb6-ignition-transport8-8.3.0/lib/libignition-transport8.so.8, not found (try using -rpath or -rpath-link)
/nix/store/039g378vc3pc3dvi9dzdlrd0i4q93qwf-binutils-2.39/bin/ld: /nix/store/a51pkq1ikrd3blpq1h7gwzaf4nw8az88-zeromq-4.3.4/lib/libzmq.so.5: undefined reference to `crypto_box_open'
/nix/store/039g378vc3pc3dvi9dzdlrd0i4q93qwf-binutils-2.39/bin/ld: /nix/store/a51pkq1ikrd3blpq1h7gwzaf4nw8az88-zeromq-4.3.4/lib/libzmq.so.5: undefined reference to `crypto_box_open_afternm'
/nix/store/039g378vc3pc3dvi9dzdlrd0i4q93qwf-binutils-2.39/bin/ld: …

ignition.transport: Fix underlinking

---

pkgs/colcon/argcomplete.nix
pkgs/colcon/bash.nix
pkgs/colcon/devtools.nix
pkgs/colcon/zsh.nix
pkgs/default.nix

This adds a few missing colcon extensions and the last commit enables already present extensions, which are enabled in typical colcon installatins (i.e. official ROS docker images).
I can imagine that the last commit, which enables parallel builds and hides build logs, might be controversial, because it could make debugging build failures harder. If this is the reason for those extension not being currently enabled, I would propose to introduce `colcon-full` with those extensions enabled. Then, we would recommend `colcon-full` for interactive sessions and keep `colcon` for Nix package building.

Add colcon extensions

---

examples/ros2-basic.nix

Previously, ros-core was not included presumably due to its dependency on ros2doctor, which depended on ifcfg package unavailable in nixpkgs. As pointed in https://github.com/lopsided98/nix-ros-overlay/issues/75#issuecomment-1508021227, this is no longer true. Since ros2cli version 0.17.0 (2022-01-25) ifcfg is no longer necessary as it was replaced by psutils [1]. This means that we can use ros-core without problems instead of manually specifying its dependencies such ros-environment, ros2topic, etc.
In addition to ros-core, colcon is a basic tool for ROS 2. Include it in the example too.
[1]: https://github.com/ros2/ros2cli/commit/cc5d6b1f9b26ada1a8f366ef7fe9534077c859c2

Update ros2-basic example to include ros-core and colcon

---

pkgs/default.nix
pkgs/ogre/1.9.x.nix

Introduce version of Ogre removed from Nixpkgs.
Required by https://github.com/lopsided98/nix-ros-overlay/issues/161
Taken from https://github.com/NixOS/nixpkgs/commit/40f52d9003c5cb4929a346529d2ff1357bd89d6c

ogre1_9: init at 1.9.1

---

distros/ros2-overlay.nix

Without this, the build fails.
See [this code in their CMakeLists.txt](https://github.com/teamspatzenhirn/rig_reconfigure/blob/b25483eff7e1dfe935fe5836386964b45500e83a/CMakeLists.txt#L13-L14).

Patch vendor git in rig_reconfigure

---

distros/build-env/default.nix

This PR changes `buildEnv` to:
- Stop passing `wrapPrograms` to `buildEnv` from Nixpkgs, preventing errors from occuring
- Allow adding custom values to `postBuild` and `passthru`
- Allow supplying custom arguments to `makeWrapper` (e.g. to set the default RMW implementation to work around #45)

Make buildEnv more flexible

---

distros/humble/ament-cmake-vendor-package/default.nix
distros/humble/generated.nix
distros/humble/raspimouse-ros2-examples/default.nix
distros/humble/rviz-common/default.nix
distros/iron/generated.nix
distros/iron/rviz-common/default.nix
distros/noetic/generated.nix
distros/noetic/qb-softhand-industry-bringup/default.nix
distros/noetic/qb-softhand-industry-control/default.nix
distros/noetic/qb-softhand-industry-description/default.nix
distros/noetic/qb-softhand-industry-driver/default.nix
distros/noetic/qb-softhand-industry-hardware-interface/default.nix
distros/noetic/qb-softhand-industry-msgs/default.nix
distros/noetic/qb-softhand-industry-srvs/default.nix
distros/noetic/qb-softhand-industry-utils/default.nix
distros/noetic/qb-softhand-industry/default.nix
distros/rolling/ament-cmake-vendor-package/default.nix
distros/rolling/generated.nix
distros/rolling/rviz-common/default.nix

Superflore Nix generator began regeneration of all packages  from ROS distro ['humble', 'iron', 'noetic', 'rolling'] from nix-ros-overlay commit 359c1c87608709cfa1c3e6a0bb6d5f0701ba82f6.
```
superflore-gen-nix --tar-archive-dir /home/runner/work/_temp/tar --output-repository-path . --upstream-branch develop --all
```
Changes:
========
Humble Changes:
---------------
* *ament-cmake-vendor-package 1.3.5-r1*
* *raspimouse-ros2-examples 2.0.0-r1*
* *rviz-common 11.2.5-r1 --> 11.2.7-r1*
Iron Changes:
-------------
* *ament-cmake-vendor-package 2.0.2-r2 --> 2.0.3-r1*
* *rviz-common 12.4.0-r2 --> 12.4.2-r1*
Noetic Changes:
---------------
* *qb-softhand-industry 1.0.8-r3*
* *qb-softhand-industry-bringup 1.0.8-r3*
* …

rosdistro sync, Fri Aug  4 19:59:18 2023

---

distros/build-ros-package/default.nix
distros/distro-overlay.nix
distros/noetic/overrides.nix
distros/ros2-overlay.nix

[It seems](https://github.com/colcon/colcon-core/blob/99c03262ad7edd4af5954c424c9248e0c4fe7307/colcon_core/task/python/build.py#L91) that colcon uses the deprecated `setup.py`-style build and installation commands to build Python ROS packages.
This changes the `ament_python` variant of `buildRosPackage` to use those commands.
Fixes #230, #273.
Closes #270.
Tested with `ros-core` from Rolling, Foxy and Noetic.

Build ROS Python packages like colcon

---

distros/distro-overlay.nix

Without this, running `ros2 run plotjuggler plotjuggler` results in:
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Stack trace (most recent call last):
#13   Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in
#12   Object "/nix/store/g7mcg164p44hzgra9sp653a34d276vw2-ros-humble-plotjuggler-3.7.1-r1/lib/plotjuggler/plotjuggler", at 0x473b04, in
#11   Object "/nix/store/1x4ijm9r1a88qk7zcmbbfza324gx1aac-glibc-2.37-8/lib/libc.so.6", at 0x7f512523db88, in __libc_start_main
#10   Object "/nix/store/1x4ijm9r1a88qk7zcmbbfza324gx1aac-glibc-2.37-8/lib/libc.so.6", at …

Wrap plotjuggler with Qt wrapper

---

distros/ros2-overlay.nix
pkgs/gazebo/default.nix

Both RViz2 and Gazebo use OGRE, which does not yet run on Wayland at all. This PR adds to their wrappers to prevent Wayland from being used.
Gazebo also has issues when its bin/ directory is not in the PATH, as it attempts to run some of its own binaries. This fixes that in the wrapper as well.

Disable Wayland in RViz2 and Gazebo, add bin/ to Gazebo PATH

---

distros/foxy/aruco-opencv/default.nix
distros/foxy/cv-bridge/default.nix
distros/foxy/overrides.nix
distros/foxy/stereo-image-proc/default.nix
distros/foxy/webots-ros2-tesla/default.nix

This PR switches the Python version of OpenCV to OpenCV 4 (as has been done in rosdep), adds `argcomplete` as a propagated build input of `ros2cli` (backported from Humble), and fixes various build errors.

Miscellaneous Foxy fixes and improvements

---

distros/foxy/overrides.nix

I think that the renaming from patchVendorGit to patchExternalProjectGit has not been made for foxy distribution because foxy distribution was removed but it was then reverted.

rename patchVendorGit to patchExternalProjectGit in foxy distribution

---

distros/build-env/default.nix

The fixupPhase is needed for shell hooks and input propagation, but other things like RPATH shrinking and shebang patching are not needed, as the original packages should have already been fixed up.
This significantly reduces `buildEnv` build times. The shebang patching in particular is quite slow.

buildEnv: Disable redundant fixup operations

---

pkgs/ignition/fuel-tools/4.nix

This aligns it to the other ones:
```
… while calling the 'derivationStrict' builtin
at /builtin/derivation.nix:9:12: (source not available)
… while evaluating derivation 'gazebo-11.14.0'
whose name attribute is located at /nix/store/rz50qm74nicyhql7wrsibvanlj5kdm78-source/pkgs/stdenv/generic/make-derivation.nix:348:7
… while evaluating attribute 'propagatedBuildInputs' of derivation 'gazebo-11.14.0'
at /nix/store/rz50qm74nicyhql7wrsibvanlj5kdm78-source/pkgs/stdenv/generic/make-derivation.nix:402:7:
401|       depsHostHostPropagated      = elemAt (elemAt propagatedDependencies 1) 0;
402|       propagatedBuildInputs       = elemAt (elemAt propagatedDependencies 1) 1;
|       ^
403|       depsTargetTargetPropagated  = elemAt (elemAt propagatedDependencies 2) 0;
error: function 'anonymous …
```

Fix overriding in ignition.fuel-tools4

---

distros/humble/overrides.nix

Without this, Humble distro is not properly detected and compilation fails.

Fix plotjuggler-ros for Humble

---

distros/humble/overrides.nix

The error messages were as follows:
In file included from /build/rosbag2-release-release-humble-rosbag2_compression-0.15.9-1/src/rosbag2_compression/compression_options.cpp:18:
/build/rosbag2-release-release-humble-rosbag2_compression-0.15.9-1/include/rosbag2_compression/compression_options.hpp:29:6: warning: elaborated-type-specifier for a scoped enum must not use the 'class' keyword
29 | enum class ROSBAG2_COMPRESSION_PUBLIC CompressionMode: uint32_t
| ~~~~ ^~~~~
|      -----
/build/rosbag2-release-release-humble-rosbag2_compression-0.15.9-1/include/rosbag2_compression/compression_options.hpp:29:54: error: found ':' in nested-name-specifier, expected '::'
29 | enum class ROSBAG2_COMPRESSION_PUBLIC CompressionMode: uint32_t
|                                                      ^
| …

Fix rosbag2-compression compile error

---

distros/build-env/default.nix

This PR adds some ROS version environment variables to the `buildEnv` wrapper. These variables are normally included by `nix-shell`, but are left out when building the wrapper.
ROS packages expect these variables to exist, and can fail when they are unset. `foxglove_bridge`, for example, crashes when `ROS_DISTRO` is unset.
See also:
- [REP 123: ROS_ETC_DIR, ROS_DISTRO environment variables and ROS_ROOT changes](https://ros.org/reps/rep-0123.html)
- [REP 149: Package Manifest Format Three Specification](https://ros.org/reps/rep-0149.html#environment-variables)

buildEnv: Add ROS version environment variables to wrapper

---

distros/distro-overlay.nix

release packages for librealsense was updated last time at September 2023 while this fix was added on Nov 2023
According to https://github.com/IntelRealSense/librealsense/pull/11917

FIX librealsense2 compile error

---

distros/ament-cmake-core-setup-hook/setup-hook.sh

The purpose of ROS-specific version of buildEnv in this overlay is to reduce the length of environment variables when using many ROS packages. However, currently it works only for ROS 1 and not for ROS 2. This commit is an attempt to fix that.
Although the change looks trivial, it took me multiple full days to figure out what to change and how. The following is my understanding of how handling of environment variables works in ROS 2 and in nix-ros-overlay and why the change in this commit works. I'm not completely sure that it's all correct so feel free to complain if not.
- Every ament_cmake ROS package contains a `$out/share/*/local_setup.sh` script, generated by ament CMake macros, which is responsible for setting environment variables required for proper function of the package under …

buildEnv: Reduce length of AMENT_PREFIX_PATH and other ROS 2 variables

---

pkgs/gazebo/default.nix

makes the derivation more pure, without this it leads to (gzclient:1568911): GLib-GIO-ERROR **: 15:37:29.803: No GSettings schemas are installed on the system, unless you happen to be lucky enough to have the right files in your environment

gazebo: add wrapGAppsHook

---

.github/workflows/build.yaml
distros/default.nix
distros/jazzy/overrides.nix

The content of `jazzy/overrides.nix` is just a copy of `rolling/overrides.nix`.
At least `ros-core` builds successfully (tested on files generated by superflore today; not yet in this repo).

Add ROS 2 Jazzy Jalisco

---

distros/humble/overrides.nix

The patch causes build failure.
Fixes #424.

rosbag2-compression: Remove patch, which is now in a released version

---

pkgs/gazebo/default.nix

Unstable ships with graphviz 10 instead of 9. Allow gazebo to compile against the newer version as well.

Allow gazebo to build against graphviz 10

---

distros/build-ros-package/default.nix

If the user has `services.nixseparatedebuginfod.enable=true` in their configuration this should allow `gdb` and friends to pull down symbols and source.
Closes #431

buildRosPackage: default separateDebugInfo to true

---

distros/ros2-overlay.nix

This fixes build issues on MacOS identified in #419. With these commits, it's possible to build `humble.ros-core` on MacOS. Unfortunately, building `ros-core` still fails on iron and rolling due to `lttng` being a dependency of `fastrtps`. I think this can be fixed, but will require more work, maybe in other repositories, so I don't try to fix it here.

Allow building ros-core for humble on MacOS

---

README.md

Currently, quite a few things are broken when ROS packages are used directly without buildEnv.
Closes #396 #401
Related #362

README: Update example flake.nix to use buildEnv

---

distros/distro-overlay.nix

This contains two fixes:
1. The first is that `ROS_DISTRO` is read from the environment in `CMakeLists.txt`. The variable is only available when `ros-environment` is included as a build input. I'm not sure how this worked before. (https://github.com/jsk-ros-pkg/jsk_recognition/pull/2836)
1. The second build fix is removing `catkin_python_setup` from `CMakeLists.txt` (https://github.com/jsk-ros-pkg/jsk_recognition/pull/2829)
Fixes #406

Fix jsk-recognition-msgs on noetic

---

flake.nix

Preserves module file location
See: https://fzakaria.com/2024/07/29/import-but-don-t-import-your-nixos-modules.html
See: https://github.com/nix-community/nixd/issues/556

Do not use import for the default module

---

distros/humble/overrides.nix

The patch doesn't apply and is not needed anymore.

Remove libstatistics-collector patch

---

distros/distro-overlay.nix
distros/humble/overrides.nix
distros/iron/overrides.nix
distros/jazzy/overrides.nix

The version in jazzy uses a different version, so we copy the original expression to {humble,iron}/overrides.nix and add an updated one to jazzy/overrides.nix.

shared-queues-vendor: Update patching of vendor URL for Jazzy

---

distros/jazzy/overrides.nix

The patch is no longer needed on jazzy.
equivalent to https://github.com/lopsided98/nix-ros-overlay/commit/252ad9fcb29fcf2ff0f3f2151c786db13266dfb0

Fix rosidl-generator-py patching.

---

distros/ros2-overlay.nix

This is needed at least for Humble and Iron. Jazzy version cannot be build due to build failures in its dependencies.
Without this change the build fails with:
-- The CXX compiler identification is GNU 13.3.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /nix/store/mpm3i0sbqc9svfch6a17179fs64dz2kv-gcc-wrapper-13.3.0/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at cmake/CPM.cmake:19 (file):
file DOWNLOAD cannot compute hash on failed download
status: [6;"Couldn't resolve host name"]
Call Stack (most recent call first):
CMakeLists.txt:8 (include)

Patch rosx-introspection to not download anything from the Internet

---

pkgs/colcon/mixin.nix
pkgs/default.nix

This adds `colcon-mixin` to the set of available extensions.
I believe the extension is useful enough, while also being mentioned by the ROS 2 docs, to warrant a place in the default set of extensions, so I added it there. I'll remove it if you disagree.
Also, I provisionally put @lopsided98 as the maintainer because the commit to nixpkgs that adds me to the set of maintainers is currently stuck together with a PR that is slow to getting merged / reviewed.

colcon-mixin: init at 0.2.3

---

distros/default.nix
distros/distro-overlay.nix

This PR reworks the Python overlay system to make changing the Python version used for a ROS distro easier.
When the top-level `rosPython` package is defined in a distro scope, it will be used instead of `python3`.
For example:
```nix
self: super:
{
rosPackages = super.rosPackages // {
jazzy = super.rosPackages.jazzy.overrideScope (rosSelf: rosSuper: {
rosPython = self.python311;
});
};
}
```
Closes #413.
Closes #379.

Allow changing the Python version in ROS distros

---

pkgs/rosinstall-generator/default.nix

Python 3.12 removes native `distutils` support, but `rosinstall-generator` requires it. This PR adds it to the `nativeBuildInputs`.
The pinned revision of Nixpkgs does not include the separate `distutils` package, though, so this is accounted for too.

python3Packages.rosinstall-generator: Add distutils to nativeBuildInputs

---

distros/humble/overrides.nix

fixes [foonathan::memory] Allocator foonathan::memory::memory_pool error, mentioned in https://github.com/lopsided98/nix-ros-overlay/issues/419#issuecomment-2196472985, see https://github.com/RoboStack/ros-humble/issues/32#issuecomment-2227591674
Tested on macOS 15.0-beta, needs to be verified on other versions and platforms

update foonathan-memory to fix memory allocation error on macOS

---

distros/ros2-overlay.nix

the ament cmake vendoring works by downloading files into the `ros2_ws/install/opt/<package>` folder, which is a *local* path. It then sets the `CMAKE_PREFIX_PATH` to point into this directory. However, the normal nixpkgs cmake setup renames the /opt/ chunk with /var/empty, which then breaks the CMAKE_PREFIX_PATH setup. since this is a local install, just dont "fix" the cmake paths.
I noticed this by trying to build https://github.com/ros2/rmw_zenoh, which uses the ament cmake vendoring, and therefore just simply does not build without this patch.
I had to apply this in the distro overlay files, as the vendoring package does not exist in foxy.

ament-cmake-vendor-package: don't 'fix' cmake files

---

distros/distro-overlay.nix
distros/ros1-overlay.nix

I have been bounding around trying to get all of the pyqt stuff to work across all of the distros for a while now... and I think this is my final solution. It seems to keep everything happy, and works even for the most current versions of everything, without requiring any huge overrides, or any patches that will break when files are updated upstream.
Some packages need specifically pyqt or pyside to be loaded by python-qt-binding. This changes the overrides to support both.
Annoyingly, in recent python-qt-binding releases, sip_configure.py, the cmake helper script, rewrites QtCoremod.sip, which is outside of the nix build area and causes a build failure. See https://github.com/ros-visualization/python_qt_binding/commit/e78372fd63eda527c9fad5fcdab8ca31eb3f36d2
This is the same patch that …

Python qt bindings support both

---

distros/build-env/default.nix

Fixes #391 
But does this break anythink else? Is this a good fix?

Add fixupPhase flag to fix the cmake copy issue

---

pkgs/openni2/default.nix

Some ROS packages depend on OpenNI2, which fails to build. I have no clue what it is and it seems unmaintained (at least by upstream), but to be able to build the depending packages, I collected a few fixes which make it build again.

OpenNI2 fixes

---

flake.nix

This gets rid of evaluation error for armv7a-darwin. It makes no sense to support this platform in this overlay. According to the discussion around around https://github.com/NixOS/nixpkgs/pull/324155#issuecomment-2362297603, it is better to support just the systems exposed by the nixpkgs flake.
Currently, these are:
- aarch64-darwin
- aarch64-linux
- armv6l-linux
- armv7l-linux
- i686-linux
- powerpc64le-linux
- riscv64-linux
- x86_64-darwin
- x86_64-freebsd
- 86_64-linux
Closes #484

Reduce the number of systems offered by the flake

---

distros/distro-overlay.nix

MRPT ROS packaging was recently split to multiple smaller ROS packages, but the source code of all of them is still maintained in the original big repo. The new packages fetch the original repo and build just a part of it. Obviously, with Nix, we have to fetch source code ourselves, instead of letting CMake do this.
This depends on #482.

Patch vendored source code of MRPT packages

---

distros/catkin-nixpkgs-prefix-path.patch
distros/ros1-overlay.nix

Alternative to #497. Heavy handed but:
`nix build .#noetic.pluginlib` works.
`nix develop .#noetic.pluginlib` and manually invoking `cmake` to build works.
Fixes #491

catkin: patch to account for NIXPKGS_CMAKE_PREFIX_PATH

---

distros/noetic/overrides.nix

After b6676bf7dc1b03afe9582c5fd99025b3a4b7f4f9 `roslint` can't find `distutils`. Force it as a dependency.

roslint: add a dependency on distutils

---

README.md
examples/flake/flake.nix
flake.nix

With this change, one can initialize a ROS project by running:
nix flake init --template github:lopsided98/nix-ros-overlay
Besides adding the template, this commit also updates the README to list the same template as the one from the flake. The listing in the README can be easily updated to match the flake.nix file by running the "mdsh" tool.

Add flake template

---

distros/distro-overlay.nix
distros/humble/overrides.nix

Replace distutils.spawn in sip_configure.py if present. For jazzy this is fixed upstream but for humble not.

[fix] replace distutils.spawn in sip_configure.py

---

README.md
flake.nix
release.nix

I've setup [a public Hydra instance](https://hydra.iid.ciirc.cvut.cz/project/nix-ros-overlay
), which builds this overlay for x86 and aarch64 linux. Currently, I consider it experimental in the sense, that I might change the configuration in the future depending on how it will behave, but it already gives useful information for users and contributors.
To make it easier to setup Hydra jobsets, I updated release.nix. It's probably not worth reading all commits, one by one, because some later commits override previous ones and I was lazy to redo things cleanly from the beginning. But the final state is hopefully understandable.
Currently, the hydra builds my fork, but once this PR is merged, I'll switch it to the upstream repo. The configuration of the jobsets is generated programmatically …

Extend release.nix and add a link to public Hydra

---

distros/jazzy/overrides.nix

See https://hydra.iid.ciirc.cvut.cz/build/241591/nixlog/1.
Among other things, this fixes `rviz`.

Fix gz-math-vendor in Jazzy

---

distros/ros2-overlay.nix

Fixes https://github.com/lopsided98/nix-ros-overlay/issues/541
Removing the flag relieves the linker in dependent packages like `ros-moveit-*` with many dependencies, since it would otherwise need to search all propagated libraries for symbols.

remove `--as-needed` propagated flag from backward-ros

---

distros/jazzy/overrides.nix
distros/rolling/overrides.nix

Same as here
https://github.com/lopsided98/nix-ros-overlay/pull/228
but for new gz-transport-vendor

gz-transport-vendor: add libsodium to buildInputs

---

distros/humble/overrides.nix

This fixes many build failures when building the overlay against nixos-unstable.
In the past NumPy core headers were under `numpy/core/include`, but in recent nixpkgs versions, the location changed to `numpy/_core/include`.
NumPy >= 2.0 also includes `numpy-config` tool. We could use the tool to get the correct path, instead of hardcoding it in the Nix expression, but I'm not sure how it would work with cross-compiling, so I'm leaving the logic as it was.

humble.rosidl-generator-py: Fix numpy include path

---

distros/humble/overrides.nix

This fixes about 160 failed builds against nixos-unstable.

humble.octomap: Fix errors related to gcc14

---

distros/jazzy/overrides.nix
distros/rolling/overrides.nix

This will be needed after merging #574.

jazzy/gz-*-vendor: Update versions in overrides to match upstream

---

distros/jazzy/overrides.nix

Fixes this error:
```
> CMake Error at CMakeLists.txt:114 (message):
>   Mismatch in ros-jazzy-gz-common-vendor version (Nix: 5.7.0, upstream:
>   5.7.1).  Fix this in overrides.nix.
```
The new hash is retrieved with `nix flake prefetch github:gazebosim/gz-common/gz-common5_5.7.1` command that returns correct old hash for the previous revision.

Fix ros-jazzy-gz-common-vendor version mismatch in cmake

---

distros/jazzy/overrides.nix

Fixes this error:
```
> CMake Error at CMakeLists.txt:114 (message):
>   Mismatch in ros-jazzy-gz-msgs-vendor version (Nix: 10.3.1, upstream:
>   10.3.2).  Fix this in overrides.nix.
```

Fix ros-jazzy-gz-msgs-vendor version when building with cmake

---

distros/jazzy/overrides.nix

Update packages in overrides of jazzy.
Following command can be used to reproduce the issue:
`NIXPKGS_ALLOW_INSECURE=1 nix develop --impure .#example-ros2-gz`

Fix example-ros2-gz

---

distros/distro-overlay.nix

Without this change, gtsam is built against a vendored copy, which is different version (3.3) than what's in nixpkgs (3.4). Dependent packages using eigen then fail with the following error:
/nix/store/lic85q2svs3ymv0zkgl727af9khm1x4l-ros-jazzy-gtsam-4.2.0-r4/include/gtsam/base/Vector.h:76:30: error: static assertion failed: Error: GTSAM was built against a different version of Eigen
76 |     GTSAM_EIGEN_VERSION_MAJOR==EIGEN_MAJOR_VERSION,
|                              ^
/nix/store/lic85q2svs3ymv0zkgl727af9khm1x4l-ros-jazzy-gtsam-4.2.0-r4/include/gtsam/base/Vector.h:76:30: note: the comparison reduces to '(3 == 4)'
This is the case for mola_state_estimation (which was recently added to ROS) as well as some unofficial ROS packages I worked with.

Build gtsam against Eigen from nixpkgs

---

distros/rolling/camera-calibration/default.nix
distros/rolling/depth-image-proc/default.nix
distros/rolling/fastdds/default.nix
distros/rolling/generated.nix
distros/rolling/image-pipeline/default.nix
distros/rolling/image-proc/default.nix
distros/rolling/image-publisher/default.nix
distros/rolling/image-rotate/default.nix
distros/rolling/image-view/default.nix
distros/rolling/launch-pytest/default.nix
distros/rolling/launch-testing-ament-cmake/default.nix
distros/rolling/launch-testing/default.nix
distros/rolling/launch-xml/default.nix
distros/rolling/launch-yaml/default.nix
distros/rolling/launch/default.nix
distros/rolling/rviz-assimp-vendor/default.nix
distros/rolling/rviz-common/default.nix
distros/rolling/rviz-default-plugins/default.nix
distros/rolling/rviz-ogre-vendor/default.nix
distros/rolling/rviz-rendering-tests/default.nix
distros/rolling/rviz-rendering/default.nix
distros/rolling/rviz-visual-testing-framework/default.nix
distros/rolling/rviz2/default.nix
distros/rolling/stereo-image-proc/default.nix
distros/rolling/tracetools-image-pipeline/default.nix

Superflore Nix generator began regeneration of all packages  from ROS distro ['humble', 'jazzy', 'noetic', 'rolling'] from nix-ros-overlay commit fd8d6a850487f007487a577cb641bc6408469e2a.
```
superflore-gen-nix --tar-archive-dir /home/runner/work/_temp/tar --output-repository-path . --upstream-branch develop --all
```
Changes:
========
Rolling Changes:
----------------
* *camera-calibration 6.0.9-r1 --> 6.0.10-r1*
* *depth-image-proc 6.0.9-r1 --> 6.0.10-r1*
* *fastdds 3.1.2-r1*
* *image-pipeline 6.0.9-r1 --> 6.0.10-r1*
* *image-proc 6.0.9-r1 --> 6.0.10-r1*
* *image-publisher 6.0.9-r1 --> 6.0.10-r1*
* *image-rotate 6.0.9-r1 --> 6.0.10-r1*
* *image-view 6.0.9-r1 --> 6.0.10-r1*
* *launch 3.7.1-r1 --> 3.8.0-r1*
* *launch-pytest …

rosdistro sync, Sat Mar  1 18:33:54 2025

---

pkgs/colcon/meson.nix
pkgs/default.nix

This is useful for building packages that use meson as a buildsystem. For example libcamera mentioned in #598.

colcon-meson: init at 0.4.5

---

distros/jazzy/overrides.nix
distros/rolling/overrides.nix

This fixes libcamera builds for jazzy and rolling. The version for humble is still broken, because its build system depends on Python module imp, which was removed from Python 3.12.
Fixes #598

libcamera: Fix builds for jazzy and rolling

---

distros/jazzy/overrides.nix

Fixes
```
> patchelf: getting info about '/nix/store/44picdxg6lxgn6d3f3ndipwc9df87a6z-ros-jazzy-gz-gui-vendor-0.0.5-r1/lib64/gz-gui-8/plugins/libGrid3D.so': No such file or directory
```

jazzy: Fix failing patchelf for gz-gui-8

---

distros/noetic/overrides.nix

Without this, `examples/turtlebot3-gazebo.nix` fails to run.
Fixes #610.

noetic.xacro: Propagate distutils

---

.github/workflows/update.yaml
.gitignore
README.md
flake.nix
maintainers/scripts/update-overlay.nix

Given that the update GitHub Action is failing for multiple weeks (fix is in #640), it might be useful for users to perform the update locally. With this PR, one can update the overlay locally by running:
nix run .#update-overlay
This executes more or less the same commands as the GitHub Action performing periodic updates. The second commit updates the action to use the same instead of duplicating the code in `update.yaml`. This is being tested in https://github.com/wentasah/nix-ros-overlay/actions/runs/15906983859/job/44864392480.
This functionality might also be useful for solving issues like #544.

Allow updating the overlay manually

---

distros/ros2-overlay.nix

This fixes build failures of 24 `lanelet2-*` packages. See the comparison against `devel` branch on my hydra:
https://hydra.iid.ciirc.cvut.cz/eval/4175?compare=lopsided98-develop&full=0

lanelet2-core: Fix compilation with Boost 1.87

---

distros/distro-overlay.nix
distros/ros1-overlay.nix

The patch, which was previously used for all distros, is now needed just for noetic.
This will be needed after next Superflore update.

Fix ompl build for ROS 2 distros

---

distros/jazzy/overrides.nix

Hi,
This fix plotjuggler build on jazzy.
mcap-vendor otherwise seems OK on humble and rolling.
I guess those `patchVendorUrl` are manually updated, otherwise feel free to close this PR.
Also, if they are manual, it could be worth working on some automation.

update jazzy mcap-vendor override

---

distros/jazzy/overrides.nix

Since this change was made after the last release, the package was broken. I applied the fix patch so it builds correctly.

jazzy: fix usb-cam

---

distros/humble/overrides.nix
distros/humble/zenoh-cpp-vendor/vendored-source.json
distros/humble/zenoh-cpp-vendor/zenoh-c.patch
distros/jazzy/overrides.nix
distros/jazzy/zenoh-cpp-vendor/zenoh-c.patch
distros/kilted/overrides.nix
distros/kilted/zenoh-cpp-vendor/vendored-source.json
distros/kilted/zenoh-cpp-vendor/zenoh-c.patch
distros/rolling/overrides.nix
distros/rolling/zenoh-cpp-vendor/vendored-source.json
distros/rolling/zenoh-cpp-vendor/zenoh-c.patch
lib/default.nix

This is a set of commits, which finally fixes build of `zenoh_cpp_vendor`. This is important, because many `kilted` packages depend on it.
This took inspiration from #558, cleaned up few things  and added changes required for the current Zenoh version.

zenoh_cpp_vendor

---

distros/distro-overlay.nix

Had the same problem as in https://github.com/lopsided98/nix-ros-overlay/issues/576, so used same solution.

rqt-bag: use wrapQtAppsHook

---

distros/ros2-overlay.nix

Using `--replace-warn` was a bad idea. Nobody noticed that the patching is broken due to upstream changes.
Closes #685

ros-gz-sim: Fix patching

---

README.md
distros/distro-overlay.nix
examples/ros2-basic.nix
examples/ros2-desktop-full.nix
examples/ros2-desktop.nix
flake.nix
lib/default.nix

The new examples will make it easier for new users to experiment with ROS. They provide basic environments for working with simpler ROS projects and official demos. The current examples are:
- `ros2-basic` corresponds to `ros-core`. We keep the example name for backward compatibility although the content changed a bit.
- `ros2-desktop` contains `desktop` metapackage.
- `ros2-desktop-full` contains `desktop-full` metapackage. Currently, it depends on insecure `freeimage` so we don't advertise it in README.
All examples have `rosDistro` parameter, which allows to switch distros easily. Also, our hydra builds variants for all distros, which will allow us to easily spot breakage in important packages [here](https://hydra.iid.ciirc.cvut.cz/jobset/nix-ros-overlay/develop-examples-x86_64).

Add new ROS 2 examples and update README
