examples/turtlebot3-gazebo.nix

Add rosbash to the example shell

---

pkgs/gazebo/7.nix
pkgs/gazebo/default.nix
pkgs/ignition/common/default.nix
pkgs/sdformat/default.nix

- Do not use pkg-config alias
- gazebo: Avoid aliases

gazebo: Fix build with allowAliases = false

---

distros/foxy/generated.nix
distros/foxy/moveit-planners-ompl/default.nix
distros/foxy/moveit-ros-perception/default.nix
distros/melodic/generated.nix
distros/melodic/moveit-ros-perception/default.nix
distros/melodic/python-orocos-kdl/default.nix
distros/noetic/generated.nix
distros/noetic/moveit-ros-perception/default.nix
distros/noetic/tesseract-environment/default.nix

Superflore Nix generator began regeneration of all packages  from ROS distro ['dashing', 'foxy', 'galactic', 'melodic', 'noetic'] from nix-ros-overlay commit 64252847bd8ec9f8c3ae1cc18c0fab5c651eb9c8.
```
superflore-gen-nix --tar-archive-dir /home/runner/work/_temp/tar --output-repository-path . --upstream-branch staging --all
```
Changes:
========
Foxy Changes:
-------------
* *moveit-planners-ompl 2.1.3-r1*
* *moveit-ros-perception 2.1.3-r1*
Melodic Changes:
----------------
* *moveit-ros-perception 1.0.6-r1 --> 1.0.8-r1*
Noetic Changes:
---------------
* *moveit-ros-perception 1.1.0-r1 --> 1.1.5-r1*
* *tesseract-environment 0.4.1-r1*
Missing Dependencies:
=====================

rosdistro sync, Sun May 30 14:39:38 2021

---

pkgs/catkin-tools/default.nix
pkgs/default.nix
pkgs/osrf-pycommon/default.nix

Packages up catkin_tools and it's dependency osrf_pycommon.
I'm pretty new to nixos and this overlay so I suspect my python dependencies might be off.

Package catkin_tools

---

distros/build-env/default.nix
pkgs/colcon/core.nix

Use makeWrapper as a native build input

---

flake.nix
overlay.nix

I think this is correct
Fixes #189

Migrate to new flake names

---

distros/distro-overlay.nix

popf: patch src to fix build

---

distros/ros2-overlay.nix

These changes allow me to run `rviz2`.
Issue #248 is related, though not completely solved by these changes.

Make rviz2 work

---

README.md

From several reported issues, it seems that people often mix `nix-ros-overlay` with incompatible versions of `nixpkgs`. The reason might be that we don't have documentation showing how to do it correctly. This is an attempt to do it for flakes.

README: Add example of using the overlay in flake.nix

---

distros/noetic/overrides.nix

noetic.mavros-extras: Add gcc-13 patch

---

distros/ros2-overlay.nix

I had to do this fix to get my humble environment working

[fix] humble: yaml-cpp-vendor

---

distros/noetic/overrides.nix

lvr both builds and runs with this.

Fix noetic.lvr2 and noetic.hdf5-map-io compilation

---

.github/workflows/update-colcon.yaml
maintainers/scripts/update-colcon.sh
pkgs/colcon/cargo.nix
pkgs/colcon/ros-cargo.nix

The workflow is run weekly (same as superflore update). An example PR generated by the workflow can be seen in my fork: https://github.com/wentasah/nix-ros-overlay/pull/1.

Add a script and Github workflow to automate colcon updates

---

distros/rolling/overrides.nix

See here: https://github.com/ros2-gbp/rosbag2-release/blob/2cc61ca16f9137b9facf9e0084978a456469be1a/CMakeLists.txt#L37
Building successfully in my environment.
See issue here: #489

rolling overlay mcap vendor url v1.4.0

---

pkgs/sdformat/9.nix

sdformat 9.10.0 -> 9.10.1

---

distros/noetic/overrides.nix

Adds missing dependencies on `noetic` for `distutils`

Add missing distutils dependencies

---

pkgs/bloom/default.nix
pkgs/default.nix
pkgs/vcstools/default.nix

Hi,
This add bloom and its vcstools required dependency.
I was able to create a new release with it: https://github.com/ros/rosdistro/pull/43276

bloom: init at 0.12.0

---

distros/distro-overlay.nix

joint-state-publisher-gui: Apply wrapQtAppsHook

---

distros/distro-overlay.nix

Hi again,
Here is a very simple attempt to fix #536

inherit eigenpy, hppfcl, and pinocchio from nixpkgs

---

distros/noetic/overrides.nix
pkgs/gazebo/default.nix

This [fixes 143 failed builds](https://hydra.iid.ciirc.cvut.cz/eval/2906?compare=lopsided98-develop&full=0) in noetic.

Noetic fixes

---

distros/ros2-overlay.nix

With this, cartographer builds at least for Humble, Jazzy and Rolling.
Closes #430

Fix cartographer for ROS 2

---

distros/noetic/overrides.nix
distros/ros1-overlay.nix

This will be needed after merging #616 to fix most new build failures.

noetic: Remove patches applied upstream

---

distros/ros2-overlay.nix

cartographer-ros: Fix compile errors
